import type { Metadata } from "next";

import "./globals.css";
import { QueryClientProviderWrapper } from "@/providers/AppProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProviderWrapper>
        <body className="antialiased">{children}</body>
      </QueryClientProviderWrapper>
    </html>
  );
}
