import type { Metadata } from "next";

import { PrivateRoute } from "@/HOC/PrivateRoute";

export const metadata: Metadata = {
  title: "Private page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrivateRoute>
        <body className="antialiased">{children}</body>
      </PrivateRoute>
    </html>
  );
}
